<a href="https://colab.research.google.com/github/champsleague/DeepLearning/blob/main/DL_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!cat /proc/meminfo

In [ ]:
!cat /proc/cpuinfo

In [ ]:
import torch
import torch.nn as nn
import torchvision.datasets as dsets

In [ ]:
# 1D Array with Pytorch

import torch
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [ ]:
print(t.dim()) #rank
print(t.shape) #shape
print(t.size()) #size
print(t[0], t[1], t[-1]) #Element
print(t[2:5], t[4:-1]) #Slicing
print(t[:2], t[3:]) #Slicing

1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [ ]:
# 2D Array with Pytorch

t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                       ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [ ]:
print(t.dim())
print(t.size())  #shape
print(t[:,1])
print(t[:,1].size())
print(t[:, :-1])

2
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


In [ ]:
import numpy as np

t = np.array([[[0,1,2],
              [3,4,5]],
             
             [[6,7,8],
              [9,10,11]]])
ft = torch.FloatTensor(t)
print(ft.shape)


import torchvision

t2 = np.array([[[0,1,2],[3,4,5]],[[6,7,8],[9,10,11]]])
ft2 = torch.from_numpy(t2).float()

print(ft2.shape)

torch.Size([2, 2, 3])
torch.Size([2, 2, 3])


In [ ]:
# Broadcasting

import numpy as np
import torch

# Same shape
m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([[2,2]])
print(m1+m2)

tensor([[5., 5.]])


In [ ]:
# Vector + Scalar
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([3])
print(m1)
print(m2)
print(m1+m2) # m2:3 -> [[3,3]]

tensor([[1., 2.]])
tensor([3.])
tensor([[4., 5.]])


In [ ]:
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([[3],[4]])
print(m1)
print(m2)
print(m1+m2)


tensor([[1., 2.]])
tensor([[3.],
        [4.]])
tensor([[4., 5.],
        [5., 6.]])


In [ ]:
#Mul vs Matmul

m1 = torch.FloatTensor([[1,2],[3,4]])
m2 = torch.FloatTensor([[1],[2]])
print('Shape of Matrix 1: ', m1.shape)
print('Shape of Matrix 2: ', m2.shape)
print(m1.matmul(m2))

print("\n")

m1 = torch.FloatTensor([[1,2], [3,4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1 : ',m1.shape)
print('Shape of Matrix 2 : ',m2.shape)
print(m1*m2)
print(m1.mul(m2))

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


Shape of Matrix 1 :  torch.Size([2, 2])
Shape of Matrix 2 :  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


In [ ]:
# Mean

t = torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [ ]:
print(t.mean())
print(t.mean(dim=0))
print(t.mean(dim=1))
print(t.mean(dim=-1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


In [ ]:
# Sum

t = torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [ ]:
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


In [ ]:
# Max, Argmax

t = torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [ ]:
print(t.max(),'\n')
print(t.max(dim=0),'\n')  # Returns two values : max and argmax
print('Max : ', t.max(dim=0)[0])
print('Argmax : ', t.max(dim=0)[1])

tensor(4.) 

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1])) 

Max :  tensor([3., 4.])
Argmax :  tensor([1, 1])


In [ ]:
print(t.max(dim=1),'\n')
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1])) 

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


In [ ]:
# Squeeze

ft = torch.FloatTensor([[0],[1],[2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [ ]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


In [ ]:
# Unsqueeze

ft = torch.Tensor([0,1,2,3])
print(ft.shape,'\n')

print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape,'\n')

print(ft.view(-1,4))
print(ft.view(-1,4).shape,'\n')

print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape,'\n')

print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape,'\n')

torch.Size([4]) 

tensor([[0., 1., 2., 3.]])
torch.Size([1, 4]) 

tensor([[0., 1., 2., 3.]])
torch.Size([1, 4]) 

tensor([[0.],
        [1.],
        [2.],
        [3.]])
torch.Size([4, 1]) 

tensor([[0.],
        [1.],
        [2.],
        [3.]])
torch.Size([4, 1]) 



In [ ]:
# Type Casting

lt = torch.LongTensor([1,2,3,4])
print(lt)

print(lt.float())

bt = torch.ByteTensor([True, False, False, True])
print(bt)

print(bt.long())
print(bt.float())

tensor([1, 2, 3, 4])
tensor([1., 2., 3., 4.])
tensor([1, 0, 0, 1], dtype=torch.uint8)
tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


In [ ]:
# Concatenate

x = torch.FloatTensor([[1,2],[3,4]])
y = torch.FloatTensor([[5,6],[7,8]])

print(torch.cat([x,y],dim=0))
print(torch.cat([x,y],dim=1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


In [ ]:
# Stacking

x = torch.FloatTensor([1,4])
y = torch.FloatTensor([2,5])
z = torch.FloatTensor([3,6])

print(torch.stack([x,y,z]))
print(torch.stack([x,y,z], dim=1))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [ ]:
# Ones and Zeros

x = torch.FloatTensor([[0,1,2], [2,1,0]])
print(x,'\n')

print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[0., 1., 2.],
        [2., 1., 0.]]) 

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
# In-place Operation

x = torch.FloatTensor([[1,2],[3,4]])

print(x.mul(2.))
print(x)
print(x.mul_(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
